/* auto-generated by gen_yolo_int8.py trunk -- YOLO int8-TFMA full-network scales.
 * FP32 first conv + FP32 head; 7 int8 hidden convs. Per-layer requant M (S_w*LAYER_SCALE);
 * S_in=S_out=1/42.5 cancel. QUANT0=42.5 exact (255==qval(6)), DEQUANT=1/42.5 for the head. */
#ifndef YOLO_INT8_SCALES_H
#define YOLO_INT8_SCALES_H
#define YOLO_SCALES_K 3  /* trunk uses the K=3 padded geometry */
#define YOLO_TRUNK_LAYERS 7
static const float YOLO_QUANT0     = 42.5f;  /* FP32 first-conv ReLU6 -> uint8 (=42.5) */
static const float YOLO_DEQUANT    = 0.0235294122f;  /* uint8 -> FP32 for the head (=1/42.5) */
static const float YOLO_REQUANT[7] = { 0.000922736246f, 0.000461368123f, 0.000922736246f, 0.000461368123f, 0.000922736246f, 0.000461368123f, 0.000922736246f };  /* per-hidden-layer int32->uint8 requant */
static const float YOLO_INV_SW[7] = { 8.46666622f, 8.46666622f, 8.46666622f, 8.46666622f, 8.46666622f, 8.46666622f, 8.46666622f };  /* per-layer 127/max|w|: on-device int8 weight quant (multiply, no fdiv) */
static const int   YOLO_RELU6_HI  = 255;  /* quantized value of 6 (== SATUINT8 upper clamp) */
#endif
